config/routes.rb
Rails.application.routes.draw do

  root 'about#home'

  get 'code', to: redirect('/software')
  get 'interests'  => 'interests#index'
  get 'about/home' => 'about#home'
  get 'about'      => 'about#about'

  resources :accounts
  resources :albums
  resources :apps
  resources :awards
  resources :addresses
  resources :artists
  resources :collections
  resources :companies
  resources :documents
  resources :emails
  resources :icons
  resources :galleries
  resources :genres
  resources :lyrics
  resources :movies
  resources :keys
  resources :notes
  resources :parties
  resources :phones
  resources :photos
  resources :pieces
  resources :places
  resources :roles
  resources :series
  resources :series_works
  resources :songs
  resources :titles
  resources :tools
  resources :variants
  resources :wields
  resources :works

  devise_for :users

  match 'status'                      => 'admin#status',    via: [:get, :post], as: 'status'
  get 'touch/:object_type/:object_id' => 'admin#touch',     as: 'touch'
  get 'exception/:id'                 => "admin#exception", as: :exception

  get 'works/:work_id/tools'     => 'works#tools',     as: 'work_tools'
  get 'works/:work_id/meta_info' => 'works#meta_info', as: 'work_meta_info'
  get 'daily-photo'              => 'photos#daily'

  get '/resume'              => 'resume#show', as:   :resume_generator
  get '/resume/blurbs'       => 'resume#blurbs', as: :resume_blurbs
  match 'settings'           => 'users#edit', via: [:get, :patch], as: :settings

  get 'artists/:slug'        => 'parties#show'

  resources :interests, path: '/'

end

app/models/users/award.rb
class Award < ApplicationRecord

  include Rangeable
  
  validates :name, presence: true
  validates :summary, presence: true
  validates :start_year, inclusion: {in: YEARS_OF_LIFE}
  validates :stop_year, inclusion: {in: YEARS_OF_LIFE}
  validates :live, inclusion: {in: BOOLEAN_OPTIONS}

  scope :sorted, -> {order("stop_year DESC")}

  def year
    start_year
  end

  def date_range
    DateRange.new(start_year, stop_year)
  end
end

app/controllers/awards_controller.rb
class AwardsController < MetaResourceController

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :official_title, :summary, :url, :live, :start_year, :stop_year)
    end
end

app/views/awards/_award.haml
- cache award do

  %section.award
    .title #{award.official_title} #{award.name}
    .dates= award.years
    %p.description= award.summary

app/views/awards/_award.html.haml
- cache award do
  %section.timeline.award
    = timeline_row(award, experience_icon)

app/views/awards/_form.html.haml
= form_for @award do |f|
  - if @award.errors.any?
    #error_explanation
      %h2= "#{pluralize(@award.errors.count, "error")} prohibited this award from being saved:"
      %ul
        - @award.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :official_title
    = f.text_field :official_title
  .field
    = f.label :summary
    = f.text_field :summary, maxlength: 255
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :live
    = f.check_box :live
  .field
    = f.label :start_year
    = f.number_field :start_year
  .field
    = f.label :stop_year
    = f.number_field :stop_year
  .actions
    = f.submit 'Save'

app/views/awards/edit.html.haml
%h1 Editing award

= render 'form'

= link_to 'Show', @award
\|
= link_to 'Back', awards_path

app/views/awards/index.html.haml
%h1 Listing awards

%table
  %thead
    %tr
      %th Name
      %th Official title
      %th Summary
      %th Url
      %th Live
      %th Start year
      %th Stop year
      %th
      %th
      %th

  %tbody
    - @awards.each do |award|
      %tr
        %td= award.name
        %td= award.official_title
        %td= award.summary
        %td= award.url
        %td= award.live
        %td= award.start_year
        %td= award.stop_year
        %td= link_to 'Show', award
        %td= link_to 'Edit', edit_award_path(award)
        %td= link_to 'Destroy', award, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Award', new_award_path

app/views/awards/new.html.haml
%h1 New award

= render 'form'

= link_to 'Back', awards_path

app/views/awards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @award.name
%p
  %b Official title:
  = @award.official_title
%p
  %b Summary:
  = @award.summary
%p
  %b Url:
  = @award.url
%p
  %b Live:
  = @award.live
%p
  %b Start year:
  = @award.start_year
%p
  %b Stop year:
  = @award.stop_year

= link_to 'Edit', edit_award_path(@award)
\|
= link_to 'Back', awards_path