config/routes.rb
Rails.application.routes.draw do

  root 'about#home'

  get 'code', to: redirect('/software')
  get 'interests'  => 'interests#index'
  get 'about/home' => 'about#home'
  get 'about'      => 'about#about'

  resources :accounts
  resources :albums
  resources :apps
  resources :awards
  resources :addresses
  resources :artists
  resources :collections
  resources :companies
  resources :documents
  resources :emails
  resources :icons
  resources :galleries
  resources :genres
  resources :lyrics
  resources :movies
  resources :keys
  resources :notes
  resources :parties
  resources :phones
  resources :photos
  resources :pieces
  resources :places
  resources :roles
  resources :series
  resources :series_works
  resources :songs
  resources :titles
  resources :tools
  resources :variants
  resources :wields
  resources :works

  devise_for :users

  match 'status'                      => 'admin#status',    via: [:get, :post], as: 'status'
  get 'touch/:object_type/:object_id' => 'admin#touch',     as: 'touch'
  get 'exception/:id'                 => "admin#exception", as: :exception

  get 'works/:work_id/tools'     => 'works#tools',     as: 'work_tools'
  get 'works/:work_id/meta_info' => 'works#meta_info', as: 'work_meta_info'
  get 'daily-photo'              => 'photos#daily'

  get '/resume'              => 'resume#show', as:   :resume_generator
  get '/resume/blurbs'       => 'resume#blurbs', as: :resume_blurbs
  match 'settings'           => 'users#edit', via: [:get, :patch], as: :settings

  get 'artists/:slug'        => 'parties#show'

  resources :interests, path: '/'

end

app/controllers/series_controller.rb
class SeriesController < MetaResourceController

  def show
    authorize(@series, :show?)
    if params[:controller] == 'series' and
      params[:action] == 'show'
      redirect_to @series.canonical_path, status: 301
    end
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(series_params_list)
    end

    def series_params_list
      [:audience,
       :description,
       :interest_id,
       :name,
       :summary,
       :type,
       images_attributes: [:data, :name]]
    end

end

app/views/series/_admin_links.html.haml
%p.admin{data: {visible_to: 'admin'}}
  %smaller.subdued
    = link_to(icon(:touch),  touch_path(series))
    = link_to(icon(:new),    new_series_work_path(series_id: series.id), rel: 'nofollow')
    = link_to(icon(:edit),   edit_series_path(series), rel: 'nofollow')
    = link_to(icon(:delete), series, :method => :delete, :data => { :confirm => 'Are you sure?' }, rel: 'nofollow')

app/views/series/_form.html.haml
= form_for @series do |f|
  - handle_errors(@series)

  = label_field(f.label(:name), f.text_field(:name))
  = label_field(f.label(:interest_id),
                f.select(:interest_id, options_from_collection_for_select(Interest.all, :id, :name, selected: @series.interest_id)))

  = label_field(f.label(:type),
              f.select(:type, options_for_select(Series::TYPES, selected: @series.type)))

  = label_field(f.label(:summary), f.text_field(:summary, maxlength: 255))
  = label_field(f.label(:description), f.text_area(:description))
  = label_field(f.label(:audience), f.check_box(:audience))
  - unless @series.new_record?
    = label_field(f.label(:image), image_fields(f, @series))

  = submit(f)

app/views/series/_series.html.haml
-# - cache series do
-#   %section.series{class: series.interest}
-#     .row
-#       .medium-3.columns.medium-offset-2.medium-text-right.title-box
-#         %h3
-#           = link_to(series.name, series)
-#         %p
-#           %span.years
-#             = series.years

-#         -# %span.titles
-#         -#   = raw(series.titles.sort_by{|t| t.sort}.map{|t| link_to(t.name, t)}.join(', '))
-#         %span.tools
-#           = raw(series.tools.map{|t| link_to(t.name, t)}.join(', '))

-#         - if series.has_image?
-#           = link_to(image_tag(series.image.url(:thumb)), series.image.url(:original), target: "_blank")

-#         %p.admin{data: {visible_to: 'admin'}}
-#           %smaller.subdued
-#             = link_to(icon(:touch), touch_path(series))
-#             = link_to(icon(:new), new_series_work_path(series_id: series.id), rel: 'nofollow')
-#             = link_to(icon(:edit), edit_series_path(series), rel: 'nofollow')
-#             = link_to(icon(:delete), series, :method => :delete, :data => { :confirm => 'Are you sure?' }, rel: 'nofollow')
-#       .medium-5.columns.end.info-box
-#         = series.decorate.artist_name
-#         - if series.description.present?
-#           %p.description= series.description

-#         = render 'works/list', works: series.works, embedded_content: true

app/views/series/edit.html.haml
- title('Editing series')

= render 'form'

= link_to 'Show', @series
\|
= link_to 'Back', series_index_path

app/views/series/index.html.haml
- title('Listing series')

= new_button(:series)

%table
  %thead
    %tr
      %th Name
      %th Summary
      %th
      %th

  %tbody
    - @series.each do |series|
      %tr
        %td= link_to(series.name, series)
        %td= series.summary
        %td= link_to icon(:edit), edit_series_path(series)
        %td= link_to icon(:delete), series, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/series/new.html.haml
- title('New series', false)

= label_field(nil, content_tag(:h1, 'New Series'))

= render 'form'

app/views/series/show.html.haml
- title(@series.name, false)

= render @series